name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency:
  group: pages
  url-cancel-running: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Copy index.html for GitHub Pages
        run: cp app/templates/index.html ./
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Build
        uses: actions/upload-pages-artifact@v3
        
      - name: Deploy
        uses: actions/deploy-pages@v3